# Generated by Django 6.0.2 on 2026-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemrequest',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
