# Generated by Django 6.0.2 on 2026-06-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manzadle_last_played',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manzadle_max_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manzadle_streak',
            field=models.IntegerField(default=0),
        ),
    ]
